import React from 'react';
import { Download, Copy, FileJson, RefreshCw, Check } from 'lucide-react';
import type { FIRDocument } from '../../services/api';
import { useChatStore } from '../../store/chatStore';
import jsPDF from 'jspdf';

interface Props {
  fir: FIRDocument;
  onRegenerate?: () => void;
}

export default function FIRActions({ fir, onRegenerate }: Props) {
  const { addToast } = useChatStore();
  const [copiedFIR, setCopiedFIR] = React.useState(false);

  const handleCopy = () => {
    const text = buildPlainText(fir);
    navigator.clipboard.writeText(text);
    setCopiedFIR(true);
    addToast('FIR copied to clipboard!', 'success');
    setTimeout(() => setCopiedFIR(false), 2000);
  };

  const handleExportJSON = () => {
    const json = JSON.stringify(fir, null, 2);
    const blob = new Blob([json], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `FIR_${fir.fir_number}.json`;
    a.click();
    URL.revokeObjectURL(url);
    addToast('FIR exported as JSON!', 'success');
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    const pageW = doc.internal.pageSize.getWidth();
    const margin = 15;
    const usableW = pageW - margin * 2;
    let y = 20;

    const addLine = (text: string, size = 10, style = 'normal', color = '#000000') => {
      doc.setFontSize(size);
      doc.setFont('helvetica', style);
      doc.setTextColor(color);
      const lines = doc.splitTextToSize(text, usableW);
      lines.forEach((line: string) => {
        if (y > 270) { doc.addPage(); y = 20; }
        doc.text(line, margin, y);
        y += size * 0.5;
      });
      y += 2;
    };

    const addHR = () => {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.setDrawColor(180, 120, 240);
      doc.line(margin, y, pageW - margin, y);
      y += 5;
    };

    // Header
    doc.setFillColor(30, 27, 75);
    doc.rect(0, 0, pageW, 30, 'F');
    doc.setFontSize(16); doc.setFont('helvetica', 'bold'); doc.setTextColor('#ffffff');
    doc.text('FIRST INFORMATION REPORT (FIR)', pageW / 2, 14, { align: 'center' });
    doc.setFontSize(9); doc.setFont('helvetica', 'normal');
    doc.text(`FIR No: ${fir.fir_number}  |  Date: ${fir.date_of_report}`, pageW / 2, 22, { align: 'center' });
    y = 38;

    addLine('COMPLAINANT DETAILS', 11, 'bold', '#5b21b6');
    addHR();
    addLine(`Name: ${fir.complainant_name}`);
    addLine(`Contact: ${fir.complainant_contact}`);
    addLine(`Police Station: ${fir.police_station}`);
    y += 4;

    addLine('INCIDENT DETAILS', 11, 'bold', '#5b21b6');
    addHR();
    addLine(`Crime Type: ${fir.crime_type}`, 10, 'bold');
    addLine(`Date: ${fir.incident_date || 'Not specified'}`);
    addLine(`Time: ${fir.incident_time || 'Not specified'}`);
    addLine(`Location: ${fir.incident_location || 'Not specified'} (${fir.location_type})`);
    addLine(`Accused: ${fir.accused_details}`);
    y += 4;

    addLine('DESCRIPTION OF INCIDENT', 11, 'bold', '#5b21b6');
    addHR();
    addLine(fir.description, 10, 'normal', '#111111');
    y += 4;

    if (fir.witness_details?.length > 0) {
      addLine('WITNESSES', 11, 'bold', '#5b21b6');
      addHR();
      fir.witness_details.forEach((w) => addLine(`• ${w}`));
      y += 4;
    }

    if (fir.property_details?.length > 0) {
      addLine('PROPERTY INVOLVED', 11, 'bold', '#5b21b6');
      addHR();
      addLine(fir.property_details.join(', '));
      if (fir.financial_loss) addLine(`Value: ${fir.financial_loss}`, 10, 'bold');
      y += 4;
    }

    addLine('LEGAL SECTIONS APPLICABLE', 11, 'bold', '#5b21b6');
    addHR();
    fir.legal_sections.forEach((sec) => {
      addLine(`${sec.section_id} — ${sec.title} (Confidence: ${Math.round(sec.confidence * 100)}%)`, 10, 'bold');
      addLine(`Punishment: ${sec.punishment}`, 9);
      addLine(sec.explanation, 9, 'normal', '#333333');
      y += 2;
    });

    y += 4;
    addLine(`Overall Confidence: ${Math.round(fir.overall_confidence * 100)}%`, 10, 'bold');
    addLine(`Recommended Action: ${fir.recommended_action}`);
    y += 6;
    addLine('Generated by NESYA AI Legal Assistant', 9, 'italic', '#888888');

    doc.save(`FIR_${fir.fir_number}.pdf`);
    addToast('PDF downloaded!', 'success');
  };

  return (
    <div className="fir-actions" style={{ flexWrap: 'wrap', gap: 6 }}>
      <button className="fir-action-btn" onClick={handleCopy} title="Copy FIR text">
        {copiedFIR ? <Check size={13} /> : <Copy size={13} />}
        Copy
      </button>
      <button className="fir-action-btn" onClick={handleExportJSON} title="Export as JSON">
        <FileJson size={13} />
        JSON
      </button>
      <button className="fir-action-btn primary" onClick={handleDownloadPDF} title="Download PDF">
        <Download size={13} />
        PDF
      </button>
      {onRegenerate && (
        <button className="fir-action-btn" onClick={onRegenerate} title="Regenerate FIR">
          <RefreshCw size={13} />
          Regenerate
        </button>
      )}
    </div>
  );
}

function buildPlainText(fir: FIRDocument): string {
  const lines = [
    '='.repeat(60),
    '         FIRST INFORMATION REPORT (FIR)         ',
    '='.repeat(60),
    `FIR Number:    ${fir.fir_number}`,
    `Date:          ${fir.date_of_report}`,
    `Police Station: ${fir.police_station}`,
    '-'.repeat(60),
    'COMPLAINANT',
    `Name:    ${fir.complainant_name}`,
    `Contact: ${fir.complainant_contact}`,
    '-'.repeat(60),
    'INCIDENT',
    `Crime:    ${fir.crime_type}`,
    `Date:     ${fir.incident_date}`,
    `Time:     ${fir.incident_time}`,
    `Location: ${fir.incident_location}`,
    `Accused:  ${fir.accused_details}`,
    '-'.repeat(60),
    'DESCRIPTION',
    fir.description,
    '-'.repeat(60),
    'LEGAL SECTIONS',
    ...fir.legal_sections.map(
      (s) => `${s.section_id} — ${s.title} (${Math.round(s.confidence * 100)}%)\n${s.explanation}`
    ),
    '='.repeat(60),
    'Generated by NESYA AI Legal Assistant',
  ];
  return lines.join('\n');
}
